name: Build and Deploy
on: [push]
# https://vuepress.vuejs.org/zh/guide/deploy.html#github-pages
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: vuepress-deploy
        uses: jenkey2011/vuepress-deploy@master
        env:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          TARGET_REPO: username/repo
          TARGET_BRANCH: master
          BUILD_SCRIPT: yarn && yarn docs:build
          # BUILD_DIR: docs/.vuepress/dist
          BUILD_DIR: dist
          CNAME: https://github.com/xxxsjan/web-note
